name: CI

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: [ '1.22' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Dependencies
        run: |
          make setup
      - name: Run build
        run: |
          make build
      - name: Run tests
        run: |
          make test
