name: Dependency-Updates

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: [ '1.22' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install shopcloud-secrethub
          make setup
      - name: Run build
        run: |
          make build
      - name: Update Dependencies
        run: |
          go get -u ./...
          go mod tidy
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "dependencies: update"
          title: "[SECURITY] Add automatic dependencies upgrade"
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: report, automated pr, auto-merge
          assignees: thecodeengine
          base: develop
          branch: security-patches
          branch-suffix: short-commit-hash
      - name: Check output environment variable
        run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"