name: Sync Proto Files

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggers

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.TOKEN }}" | gh auth login --with-token
          
      - name: Sync proto files
        run: make sync-proto
        
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync proto files from upstream repositories'
          title: 'chore: Automated proto file sync'
          body: |
            ## Automated Proto File Sync
            
            This PR contains the latest proto file updates from upstream repositories.
            
            ### Changes
            The following proto files have been synchronized:
            - sagehub/v1/sagehub.proto
            - contenthub/v1/contenthub.proto
            - eventhub/v1/eventhub.proto
            - heartbeathub/v1/heartbeathub.proto
            - imagehub/v1/imagehub.proto
            - mailhub/v2/mailhub.proto
            - metahub/v1/metahub.proto
            - notificationhub/v1/notificationhub.proto
            - supplierhub/v1/supplierhub.proto
            - warehousebrainhub/v1/warehousebrainhub.proto
            
            Please review the changes before merging.
          branch: auto/proto-sync
          delete-branch: true
          labels: |
            automated
            proto-sync
            dependencies